# -*- coding: utf-8 -*-
"""appointment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YzttIQjC6aXMtaH2Qit4B_PV1cBbZva3
"""

class Appointment:
    def __init__(self, day_of_week, start_time_hour):
        # hidden properties
        self.__client_name = ""
        self.__client_phone = ""
        self.__appt_type = 0    # 0 = Available
        self.__day_of_week = day_of_week
        self.__start_time_hour = int(start_time_hour)

    # getters method
    def get_client_name(self):
            return self.__client_name

    def get_client_phone(self):
        return self.__client_phone

    def get_appt_type(self):
        return self.__appt_type

    def get_day_of_week(self):
        return self.__day_of_week

    def get_start_time_hour(self):
        return self.__start_time_hour

    # setters method

    def set_client_name(self, new_name):
        self.__client_name = new_name

    def set_client_phone(self, new_phone):
        self.__client_phone = new_phone

    def set_appt_type(self, new_type):
        self.__appt_type = int(new_type)

   #get appointment type description
   def get_appt_type_desc(self):
    if self.__appt_type == 0:
            return "Available"
        elif self.__appt_type == 1:
            return "Mens Cut"
        elif self.__appt_type == 2:
            return "Ladies Cut"
        elif self.__appt_type == 3:
            return "Mens Colouring"
        elif self.__appt_type == 4:
            return "Ladies Colouring"
        else:
            return "Unknown"

  # get the end time of the hours of the appointment
  def get_end_time_hour(self):
    return self.__start_time_hour+1

  # get the schedule information
  def schedule(self, client_name, client_phone, appt_type):
    self.__client_name =client_name
    self.__client_phone =client_phone
    self.__appt_type = int(appt_type)
  # cancel the appointment
  def cancel(self):
    self.__client_name =""
    self.__client_phone =""
    self.__appt_type = 0
  # format the record
  def format_record(self):
    return return f"{self.__client_name},{self.__client_phone},{self.__appt_type},{self.__day_of_week},{self.__start_time_hour}"
  # __str__ method
  def __str__(self):
    return return f"{self.__client_name:>15}{self.__client_phone:>20}  {self.__day_of_week:>10}  {self.__start_time_hour:>4} '-' {self.get_end_time_hour():>4} {self.get_appt_type_desc():>10}"