# -*- coding: utf-8 -*-
"""appt_manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZI50q9iJCKa9kpXxNTriU0T83PrA52df
"""

import  appointment, os


def main:
  def create_weekly_calendar(appt_list):
    appt_list.clear()
    MIN_AVAILABLE_HOUR=9
    MAX_AVAILABLE_HOUR=16
    days_order=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
    for day in days_order:
      for hour in range(MIN_AVAILABLE_HOUR,MAX_AVAILABLE_HOUR+1):
        appt=Appointment(day,hour)
        appt_list.append(appt)
  def load_scheduled_appointments(appt_list):
    filename=input("Enter appointment filename to load: ")
    while not os.path.exists(filename):
      print("File not found,Please try again.")
      filename=input("Enter appointment filename to load: ")
    file=open(filename,"r")
    count=0
    for line in file:
      line=line.strip()
      if line=="":
        continue
      parts=line.split(",")
      if len(parts)!=5:
        continue
      client_name=parts[0]
      client_phone=parts[1]
      appt_type=int(parts[2])
      day_of_week=parts[3]
      start_time_hour=int(parts[4])
      appt=find_appointment_by_time(appt_list,week_of_day,start_time_hour)
      if appt is not None:
        appt.schedule(client_name,client_phone,appt_type)
        count +=1
    file.close()
    return count

  def print_menu():
    print("="*40)
    print("Hair Salon Appointment Manager")
    print("="*40)
    print("1) Schedule an appointment")
    print("2) Find appointment by name")
    print("3) Print calendar for a specific day")
    print("4) Cancel an appointment")
    print("5) Change an appointment")
    print("6) Calculate total fees for a day")
    print("7) Calculate total weekly fees")
    print("9) Exit the system")
    valid_choices = ["1", "2", "3", "4", "5", "6", "7", "9"]
    choice = input("Enter your selection: ")
    while choice not in valid_choices:
        print("Invalid choice. Please try again.")
        choice = input("Enter your selection: ")
    return choice

  def find_appointment_by_time(appt_list,week_of_day,start_time_hour):
    if week_of_day=="":
      return None
    for appt in appt_list:
      if(appt.get_day_of_week()==week_of_day and appt.get_start_time_hour()==int(start_time_hour)):
        return appt
    return None

  def show_appointments_by_name(appt_list,search_name):
    found=False
    for appt in appt_list:
      if (search_name !="" and appt.get_client_name().lower()==search_name.lower()):
        print(appt)
        found=True
    if not found:
      print("No appointments found for that name.")

  def show_appointments_by_day(appt_list,search_day):
    if search_day=="":
      print("Invalid day or salon is closed.")
      return
    found=False
    for appt in appt_list:
      if (search_day !="" and appt.get_week_of_day()==search_day):
        print(appt)
        found=True
    if not found:
      print("No appointments found for that day.")